
# 输出到控制台
zlog.console.name=CONSOLE
zlog.console.enable=true
zlog.console.level=TRACE
zlog.console.pattern=[%DATE_TIME]-[%LEVEL]-[%THREAD]-[%CLASS_NAME::%METHOD@%LINE_NUMBER] : [%MESSAGE]

# 输出到文件
zlog.file.name=FILE
zlog.file.enable=true
zlog.file.level=TRACE
zlog.file.pattern=[%DATE_TIME]-[%LEVEL]-[%THREAD]-[%CLASS_NAME::%METHOD@%LINE_NUMBER] : [%MESSAGE]
# 文件目录
zlog.file.filePath=E:/zlog2/
# 日志文件名称
zlog.file.fileName=zlog2.log
# 单个日志文件最大多少MB
zlog.file.fileSize=20